services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: loja
      POSTGRES_PASSWORD: loja
      POSTGRES_DB: loja
    ports:
      - '5432:5432'
    volumes:
      - dados:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U loja']
      interval: 5s
      retries: 10

volumes:
  dados:
